@extends('layouts.auth',['title' => 'Certificate'])
@section('content')
<?php $names = [
    "Carolyne Nyachiro",
    "Sarah Thoya",
    "Agness White",
    "Silvia Mutwiwa",
    "Eugine Ochieng",
    "Lester Otara",
    "Naomy Jerotich",
    "Delvin Nyakweba1600",
    "Doreen Nyakweba",
    "Lynne Omondi",
    "Makori Elizabeth",
    "Edimon Ombati",
    "Marbel Jumanne",
    "Trizzor Nyaboke",
    "Lenza Issa",
    "Issa Samwel",
    "Joshua Morara",
    "Geofry  Ngari",
    "Gregorian Odhiambo",
    "Claudia Otara",
    "Christine James",
    "Solomon Amisi",
    "Waley Josua",
    "Violavaida Omondi",
    "Stacy Akinyi",
    "Esther Nzilani",
    "Juliana sadimba",
    "John Maranga",
    "Sandra Omondi",
    "Filgona Noreen",
    "Gloria Masinga",
    "Stephen Opiata",
    "Stephen Bogomba",
    "Adrian gift",
    "Nathan Magero",
    "Belinda Owiso",
    "Becky Kerubo",
    "Davis Ndeke",
    "Askah Rasugu",
    "Joshua Gikemi Ragira",
    "Amos Minyonga",
    "Samwel Kiche",
    "Ruth Jepkorir",
    "Innocent Gilya",
    "Hope Abuya",
    "Alex Okemwa",
    "Lewis Ndung'u",
    "Innocent Gilya",
    "Vallary Atieno ",
    "Will Ochieng'",
    "Gybson Kiplangat",
    "Peter Oyaro",
    "John Orechi",
    "Joshua Mekubo",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
]; ?>

@foreach ($names as $name)
<div class="mb-2" style="height: 100vh; width: 100%;display:inline-block;">
    <p style="font-size: 2rem; font-weight: bold; text-align:center;z-index:2;position:relative;top:35%;text-transform:uppercase;font-family:'Lucida Handwriting', cursive;;">{{ $name}}</p>
    <img src="/storage/images/cert.png" alt="" style="width: 100vw;height:90vh;object-fit:contain;">
</div>
@endforeach
@endsection